### ISSUE TITLE
text in app on launch screen / provider "choose your profile"

### ISSUE THREAD

**Issue by ghost** [eduvpn/artwork#3]
"you will be redirected to your browser for your credentials."

This is not really accurate. Maybe something like: "Your browser will be opened for you to authorize the eduVPN application".  Although, that may be too vague. There has to be a better way to be clear and correct...

**Comment by ghost** [comment]
And actually, it is not true. You won't be redirected, you will be chosen either the country flags or the list of insitutes... maybe this whole text can disappear?

**Comment by ghost** [comment]
Also, you don't choose your profile there... you choose a provider, or by profile you mean something else than the VPN profile from the instance/provider :-) confusing!

**Comment by sveeke** [comment]
How about from now on we make it:

VPN type _(e.g. Secure Internet or Institute Access)_
Provider _(e.g. SURFnet, NORDUnet or University of Amsterdam)_
Profile _(e.g. Publications, Network Operations, Teachers VPN or Students)_

Of course other suggestions are also welcome!
